### ISSUE TITLE
Add CloudFormation Rollback Alarms/Triggers

### ISSUE THREAD

**Issue by brettstack** [wizeline/serverless-fullstack#11]
CloudFormation should automatically roll back when the 5xx alarms fire.

**Comment by brettstack** [comment]
Documentation here https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_RollbackConfiguration.html

```
RollbackConfiguration:
  MonitoringTimeInMinutes: 30
  RollbackTriggers:
  - Arn: !GetAtt MyAlarm.Arn
    Type: AWS::CloudWatch::Alarm
  - Arn: !GetAtt MySecondAlarm.Arn
    Type: AWS::CloudWatch::Alarm
```
